### ISSUE TITLE
NoMethodError - undefined method `init_haml_helpers' after upgrading to version 6.1.1 from 4.0.5

### ISSUE THREAD

**Issue by yamini0312** [haml/haml#1127]
Hello, 
After upgrading from version 4.0.5 to 6.1.1 the error `NoMethodError: undefined method 'init_haml_helpers'`  occurs where  `init_haml_helpers` is used.

I have used this method something like below :
```
def initialize(object, view)
    super(object)
    view.class_eval { include Haml::Helpers }
    view.init_haml_helpers
    @view = view
  end
```

Rails version: ~> 4.2.11
Ruby version: 2.4.10

It looks like `init_haml_helpers` was completely removed from the gem , so what is the alternative?
[(https://github.com/haml/haml/blob/main/CHANGELOG.md#600)](https://github.com/haml/haml/blob/main/CHANGELOG.md#600)

How could I solve this problem?

**Comment by k0kubun** [comment]
That capability is no longer supported since asking templated code to define methods hurts the performance. From v6, if you need helpers, you should find one from the framework you're using, or define what you need yourself. For example, if you use Rails, they have helpers like `content_tag` by default, and many of them overlap what Haml used to have. You can also define what's missing on `XxxHelper`. Whatever framework you use, there should be a class that evaluates Ruby code compiled from Haml templates, and you should be able to define helpers on that class.
