### ISSUE TITLE
Haml 3.1.0 and Kaminari 0.12 = Bug

### ISSUE THREAD

**Issue by FlyboyArt** [haml/haml#380]
Kaminari 0.12 was working fine with Haml 3.0.25 and when Haml 3.1.0 was released a few hours ago, Kaminari breaks at:

kaminari-0.12.0/app/views/kaminari/_paginator.html.haml

with a: undefined method `parent' for nil:NilClass error

I'll post this on the Kaminari page as well.

thx, Art
