### ISSUE TITLE
Regression: undefined method `render' with Spree

### ISSUE THREAD

**Issue by shaicoleman** [haml/haml#570]
Worked with 3.2.0.alpha.13, but is broken with 3.2.0.alpha.14 and 3.2.0.beta.1. When using Spree 1.1.2

```
undefined method `render' for #<Object:0xdd11598>    

(haml):4:in `block in render'
haml (3.2.0.alpha.14) lib/haml/engine.rb:129:in `eval'
haml (3.2.0.alpha.14) lib/haml/engine.rb:129:in `render'
deface (0.9.1) lib/deface/haml_converter.rb:4:in `result'
deface (0.9.1) lib/deface/applicator.rb:16:in `apply'
deface (0.9.1) lib/deface/action_view_extensions.rb:8:in `initialize'
actionpack (3.2.6) lib/action_view/template/resolver.rb:135:in `new'
actionpack (3.2.6) lib/action_view/template/resolver.rb:135:in `block in query'
actionpack (3.2.6) lib/action_view/template/resolver.rb:131:in `map'
actionpack (3.2.6) lib/action_view/template/resolver.rb:131:in `query'
actionpack (3.2.6) lib/action_view/template/resolver.rb:117:in `find_templates'
actionpack (3.2.6) lib/action_view/template/resolver.rb:46:in `block in find_all'
actionpack (3.2.6) lib/action_view/template/resolver.rb:77:in `cached'
actionpack (3.2.6) lib/action_view/template/resolver.rb:45:in `find_all'
actionpack (3.2.6) lib/action_view/path_set.rb:65:in `block (2 levels) in find_all'
actionpack (3.2.6) lib/action_view/path_set.rb:64:in `each'
actionpack (3.2.6) lib/action_view/path_set.rb:64:in `block in find_all'
actionpack (3.2.6) lib/action_view/path_set.rb:63:in `each'
actionpack (3.2.6) lib/action_view/path_set.rb:63:in `find_all'
actionpack (3.2.6) lib/action_view/path_set.rb:58:in `find'
actionpack (3.2.6) lib/action_view/lookup_context.rb:109:in `find'
actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:77:in `block in resolve_layout'
actionpack (3.2.6) lib/action_view/lookup_context.rb:130:in `with_fallbacks'
actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:3:in `with_fallbacks'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:77:in `resolve_layout'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:86:in `resolve_layout'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:69:in `block in find_layout'
actionpack (3.2.6) lib/action_view/lookup_context.rb:228:in `with_layout_format'
actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:3:in `with_layout_format'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:69:in `find_layout'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:53:in `render_with_layout'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.6) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.6) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.6) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.6) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.6) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.6) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.6) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.6) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.6) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/usr/local/rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/benchmark.rb:310:in `realtime'
activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:39:in `render'
actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (3.2.6) lib/action_controller/metal/responder.rb:232:in `default_render'
actionpack (3.2.6) lib/action_controller/metal/responder.rb:160:in `to_html'
spree_core (1.1.2) lib/spree/core/responder.rb:19:in `to_html'
actionpack (3.2.6) lib/action_controller/metal/responder.rb:153:in `respond'
actionpack (3.2.6) lib/action_controller/metal/responder.rb:146:in `call'
spree_core (1.1.2) lib/spree/core/respond_with.rb:20:in `respond_with'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/spree_core-1.1.2/app/controllers/spree/home_controller.rb:9:in `index'
actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.6) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.6) lib/active_support/callbacks.rb:469:in `_run__726098161__process_action__147126464__callbacks'
activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.6) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.6) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.6) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.6) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in `call'
spree_core (1.1.2) lib/spree/core/middleware/redirect_legacy_product_url.rb:13:in `call'
spree_core (1.1.2) lib/spree/core/middleware/seo_assist.rb:27:in `call'
railties (3.2.6) lib/rails/engine.rb:479:in `call'
railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in `call'
warden (1.1.1) lib/warden/manager.rb:35:in `block in call'
warden (1.1.1) lib/warden/manager.rb:34:in `catch'
warden (1.1.1) lib/warden/manager.rb:34:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.1) lib/rack/etag.rb:23:in `call'
rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in `call'
activerecord (3.2.6) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `_run__418651959__call__259458353__callbacks'
activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.6) lib/rails/rack/logger.rb:26:in `call_app'
railties (3.2.6) lib/rails/rack/logger.rb:16:in `call'
quiet_assets (1.0.1) lib/quiet_assets.rb:20:in `call_with_quiet_assets'
actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.1) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.1) lib/rack/lock.rb:15:in `call'
actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.6) lib/rails/engine.rb:479:in `call'
railties (3.2.6) lib/rails/application.rb:220:in `call'
railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
passenger (3.0.12) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
passenger (3.0.12) lib/phusion_passenger/utils.rb:479:in `safe_fork'
passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in `synchronize'
passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.12) helper-scripts/passenger-spawn-server:99:in `<main>'
```
