### ISSUE TITLE
Wrong order of method aliasing

### ISSUE THREAD

**Issue by sleaz0id** [haml/haml#915]
When updating Rails 5.0 to 5.1 I came across the following problem.

```=> Booting Puma
=> Rails 5.1.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/mat/.rvm/gems/ruby-2.4.0/gems/brakeman-3.6.1/bundle/ruby/2.3.0/gems/haml-4.0.7/lib/haml/template.rb:13:in `alias_method': undefined method `precompiled_method_return_value' for class `Haml::Compiler' (NameError)
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/brakeman-3.6.1/bundle/ruby/2.3.0/gems/haml-4.0.7/lib/haml/template.rb:13:in `<class:Compiler>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/brakeman-3.6.1/bundle/ruby/2.3.0/gems/haml-4.0.7/lib/haml/template.rb:9:in `<module:Haml>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/brakeman-3.6.1/bundle/ruby/2.3.0/gems/haml-4.0.7/lib/haml/template.rb:8:in `<top (required)>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/haml-5.0.0/lib/haml/railtie.rb:15:in `block (2 levels) in <class:Railtie>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:45:in `instance_eval'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:45:in `execute_hook'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:35:in `block in on_load'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:34:in `each'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:34:in `on_load'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/haml-5.0.0/lib/haml/railtie.rb:14:in `block in <class:Railtie>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `run'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/application.rb:353:in `initialize!'
	from /Users/mat/Dropbox/Projekty/aga/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:24:in `app'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:42:in `start'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:130:in `block in perform'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:125:in `tap'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:125:in `perform'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/command/base.rb:63:in `perform'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/command.rb:44:in `invoke'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/railties-5.1.0/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/mat/Dropbox/Projekty/aga/bin/rails:9:in `require'
	from /Users/mat/Dropbox/Projekty/aga/bin/rails:9:in `<top (required)>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /Users/mat/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/mat/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/mat/Dropbox/Projekty/aga/bin/spring:14:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'```

**Comment by teeparham** [comment]
Your call stack has two different versions of haml referenced. Try restarting spring.

**Comment by sleaz0id** [comment]
It was my first opportunity to use `rails restart` command. Thank you and sorry for false alarm :).
