### ISSUE TITLE
Replacement for Haml::AttributeParser available?

### ISSUE THREAD

**Issue by raxod502** [haml/haml#1085]
Getting this when upgrading from 5.x to 6.x of haml:

```
NameError: undefined method `available?' for class `Haml::AttributeParser'
```

I notice that, indeed, this method has been removed. What should we use instead?

The online docs (https://haml.info/docs/yardoc/Haml/AttributeParser.html), which I understand per https://github.com/haml/haml/issues/1064 is not updated for 6.x, suggests that `available?` should "return true if AttributeParser.parse can be used". Does the absence of this method mean that in haml 6.x we can always expect AttributeParser.parse to be available?

**Comment by k0kubun** [comment]
`AttributeParser` is designed for an optimization and I'm not sure if it's necessarily useful as a public API, but I'm okay with resurrecting this for now. Added this back at https://github.com/haml/haml/commit/b3cdafdaf09433af4b0988a533414d9409e72f2a.

**Comment by k0kubun** [comment]
Released as v6.0.1.
